version: 2.1

jobs:
  build_and_publish:
    parameters:
      docker_tag:
        type: string
        default: $CIRCLE_SHA1

      update_latest:
        type: boolean
        default: false

    docker:
      - image: docker:latest

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Authenticate with Dockerhub
          command: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

      - run:
          name: Build Docker container
          command: docker build -t ailabsteam/infrastructure-tools:<< parameters.docker_tag >> .

      - run:
          name: Publish built Docker container
          command: docker push ailabsteam/infrastructure-tools:<< parameters.docker_tag >>

      - when:
          condition: << parameters.update_latest >>
          steps:
            - run:
                name: Publish build Docker container with `latest` tag
                command: |
                  docker tag \
                    ailabsteam/infrastructure-tools:<< parameters.docker_tag >> \
                    ailabsteam/infrastructure-tools:latest

                  docker push ailabsteam/infrastructure-tools:latest

workflows:
  build_and_publish:
    jobs:
      - build_and_publish

  build_and_publish_tag:
    jobs:
      - build_and_publish:
          docker_tag: $CIRCLE_TAG
          update_latest: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
