version: 2.1

jobs:
  build_and_publish:
    parameters:
      docker_tag:
        type: string
        default: $CIRCLE_SHA1

    docker:
      - image: docker:latest

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Authenticate with Dockerhub
          command: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

      - run:
          name: Build Docker container
          command: docker build -t ailabsteam/infrastructure-tools:<< parameters.docker_tag >> .
      - run:
          name: Publish built Docker container
          command: docker push ailabsteam/infrastructure-tools:<< parameters.docker_tag >>

workflows:
  build_and_publish:
    jobs:
      - build_and_publish

  build_and_publish_tag:
    jobs:
      - build_and_publish:
          docker_tag: $CIRCLE_TAG
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
